universal-crossplane:
  externalSecretStoresEnabled: false
  image:
    repository: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/crossplane
    tag: v1.17.1-up.1
    pullPolicy: IfNotPresent
  bootstrapper:
    image:
      repository: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/uxp-bootstrapper
      tag: v1.17.1-up.1
      pullPolicy: IfNotPresent
    config:
    # -- Enable debug mode for bootstrapper.
    debugMode: true
  extraObjects:
  # AWS Provider Family
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-family-aws
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-family-aws:v1.23
      skipDependencyResolution: true

   # IAM Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-aws-iam
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-iam:v1
      skipDependencyResolution: true
      
  # CloudWatch Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-aws-cloudwatch
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-cloudwatchevents:v1
      skipDependencyResolution: true
      
  # SNS Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-aws-sns
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-sns:v1
      skipDependencyResolution: true
      
  # SQS Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-aws-sqs
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-sqs:v1
      skipDependencyResolution: true  
  
  # ProviderConfig for AWS AuthN
  - apiVersion: aws.upbound.io/v1beta1
    kind: ProviderConfig
    metadata:
      name: default
    spec:
      credentials:
        source: IRSA
